SELECT DESCP, UKURAN 
FROM MASTER_NAS_M mnm 
WHERE lower(mnm.DESCP) LIKE '%lifebuoy b.w%'
AND mnm.UKURAN = 250


SELECT TR_MEMBERS, TR_PLU_PCS, TR_DATE, TR_JAM_TRANSAKSI, NVL(TR_TYPE,'N'), NVL(rt.tr_flag_rpt,'KOSONG') AS TR_FLAG_RPT FROM RPT_TRANS rt WHERE
rt.TR_DATE BETWEEN '01jan21' AND '04jan21'
AND rt.DW_BRANCH_CODE = 'TZ01'
and NVL(rt.tr_members,'N') not like '%#%'
and NVL(rt.tr_members,'N') not in (select mcp_no_kartu from report.rpt_ms_ssp)
and NVL(rt.tr_type,'N') not like '%R%'
and NVL(rt.tr_type,'-') not like '%X%'
and NVL(rt.tr_type,'-') not like '%V%'
and NVL(rt.tr_flag_rpt,'N') not in ('S','B','X')
and NVL(rt.tr_type, '-') not in ('S', 'B')
and length(rt.tr_members) in (10,12,16)

SELECT * FROM report.RPT_TRANS rt 
WHERE rt.TR_MEMBERS = '9990010044784645'
--AND rt.TR_PLU_PCS = '120764'
AND rt.TR_DATE BETWEEN '29Aug20' AND '29Aug20'

--AND DW_BRANCH_CODE = 'TZ01'
--AND LOG_PROMO IS NOT NULL 


SELECT * FROM report.MASTER_PLU_ALFAGIFT	
WHERE lower(MPA_DESC) LIKE 'sgm%'



SELECT count(*)
--DATE1 tanggal, 
--char2 MEMBER,
--char1 toko, 
--num1 kasir, 
--num2 bon, 
--char4 invoice,  
--char3 plu, 
--descp_sub_dept
--num3 sales, 
--num4 qty
FROM ZTAMPUNGAN 
WHERE PK = 'susubayi'



SELECT CHAR1, CHAR2, CHAR3 FROM report.ZTAMPUNGAN z
WHERE z.PK = 'alfagift_member_temp'

DELETE FROM report.ZTAMPUNGAN z 
WHERE z.PK = 'alfagift_member_temp'



SELECT * FROM report.RPT_TRANS rt 
WHERE rt.TR_MEMBERS = '9990010370818635'
AND rt.TR_DATE BETWEEN '31dec20' AND '31dec20'
AND DW_BRANCH_CODE = 'TZ01'





SELECT est.ELS_RECEIPT, est.ELS_SMS_REGISTRATION_CODE, esmp.MSO_DESCP, esmp.MSO_KET, esmp.MSO_CREATE_USER 
FROM ELS_SMS_TRANS est 
LEFT JOIN ELS_SMS_MS_PROMO esmp 
ON est.ELS_MSO_ID  = esmp.MSO_ID 
WHERE est.ELS_SMS_REGISTRATION_CODE = 'BEDAE676AXBH'

SELECT * FROM ELS_SMS_MS_PROMO esmp 
WHERE ESMP.MSO_ID = 32317

SELECT * FROM MS_EMPLOYEE me 
WHERE me.NIK = 1017098020

SELECT * FROM ELS_SMS_TRANS est
WHERE est.ELS_SMS_REGISTRATION_CODE = 'BEDAE676AXBH'

SELECT * FROM RPT_TRANS rt 
WHERE rt.NOREF IS NOT NULL
AND TR_DATE BETWEEN '1feb21' AND '1mar21'
AND TR_KD_STORE IS NULL


SELECT * FROM MASTER_PLU_ALFAGIFT mpa 
WHERE MPA_PLU = 6171


SELECT * FROM ALFAGIFT_MASTER_REWARD amr 
ORDER BY AMR_UPDATE_DATE DESC



CREATE TABLE ALFAGIFT_VOUCHER_USED (
	voucher_id VARCHAR2(50),
	reg_code VARCHAR2(50),
	ponta_id VARCHAR2(50),
	no_hp VARCHAR2(50),
	email VARCHAR2(100),
	claim_date DATE,
	create_date DATE DEFAULT SYSDATE,
	PRIMARY KEY(voucher_id)
)

DROP TABLE ALFAGIFT_VOUCHER_USED
 
ALTER TABLE CX_PEOPLE
ADD CONSTRAINT PK_ALFAGIFT_VOUCHER_USER PRIMARY KEY ("ID")


ALTER TABLE ALFAGIFT_VOUCHER_USED 
ADD TRO_KD_STORE VARCHAR2(4);


SELECT * FROM ZTAMPUNGAN z 
WHERE z.PK = 'alfagift_member_temp'


insert into ALFAGIFT_VOUCHER_USED (voucher_id, reg_code, ponta_id, no_hp, email, claimed_at, create_date)
VALUES ('5fbe344ac697f5b4acb0601d', 'C06594BBDVWJ', '9990013049553987', '085156472861',
'noviaranie11@gmail.com', 
TO_DATE('2020-12-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss'), 
TO_DATE('2021-03-10 04:21:18', 'yyyy-mm-dd hh24:mi:ss'))


--DELETE FROM ALFAGIFT_VOUCHER_USED avu 


SELECT * FROM ALFAGIFT_VOUCHER_USED avu
WHERE CLAIM_DATE BETWEEN  TO_DATE('2021-03-10 00:00:00', 'yyyy-mm-dd hh24:mi:ss')
AND TO_DATE('2021-03-11 00:00:00', 'yyyy-mm-dd hh24:mi:ss')


SELECT * FROM ALFAGIFT_VOUCHER_USED avu
--WHERE REG_CODE = 'B3FBB0248UMA'
ORDER BY CLAIM_DATE DESC

DELETE FROM ALFAGIFT_VOUCHER_USED avu
WHERE VOUCHER_ID  = 'S-210130-AGSJPWW'


SELECT * FROM RPT_TRANS rt 
--WHERE rt.TR_DATE BETWEEN '01mar21' AND '02mar21'
WHERE DW_BRANCH_CODE = '20U5'
--WHERE TR_KD_STORE = '20U5'

struk
TR_KD_STORE + TR_KODE_KASIR + TR_NO_BON


SELECT * FROM report.MASTER_ITEM mi 
WHERE mi.ITEM_N = 406643

SELECT * FROM MASTER_STORE_V msv 
--WHERE KD_STORE = '2001'


